import gleeunit/should

import aoc/day8

const example_input = "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"

pub fn part1_test() {
  day8.part1(example_input) |> should.equal(14)
}

pub fn part2_test() {
  day8.part2(example_input) |> should.equal(34)
}
